source 'https://git.coding.net/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '8.0'

target 'WQAVPlayer_Example' do
  pod 'WQAVPlayer', :path => '../'

  target 'WQAVPlayer_Tests' do
    inherit! :search_paths

    
  end
end
